const dataOne = [
  {
    id: 0,
    question: "In which continent is located Saint Lucia?",
    answerA: ["Asia", false],
    answerB: ["Europe", false],
    answerC: ["America", true],
    answerD: ["Africa", false],
  },
  {
    id: 1,
    question: "The first news paper in the world was started by?",
    answerA: ["Japan", false],
    answerB: ["China", true],
    answerC: ["England", false],
    answerD: ["India", false],
  },

  {
    id: 2,
    question: "When did the World War 1 started?",
    answerA: ["27/06/1913", false],
    answerB: ["11/11/1915", false],
    answerC: ["09/08/1915", false],
    answerD: ["28/07/1914", true],
  },
  {
    id: 3,
    question: "Which is the longest river in Africa?",
    answerA: ["Congo river", false],
    answerB: ["Nile river", true],
    answerC: ["Zambesi river", false],
    answerD: ["Kasai river", false],
  },
  {
    id: 4,
    question: `Which movie won "Best Film" in 2018 Oscars?`,
    answerA: ["The shape of water", true],
    answerB: ["Moonlight", false],
    answerC: ["Green book", false],
    answerD: ["A Star is born", false],
  },
  {
    id: 5,
    question: `Who painted "The Starry Night" in 1889?`,
    answerA: ["Piet Mondrian", false],
    answerB: ["Willem de Kooning", false],
    answerC: ["Vincent van Gogh", true],
    answerD: ["Hendrick ter Brugghen", false],
  },
  {
    id: 6,
    question: `In what year did the Wall Street Crash take place?`,
    answerA: ["1925", false],
    answerB: ["1929", true],
    answerC: ["1932", false],
    answerD: ["1927", false],
  },
  {
    id: 7,
    question: `What is the hottest planet in the Solar System?`,
    answerA: ["Venus", true],
    answerB: ["Mars", false],
    answerC: ["Jupiter", false],
    answerD: ["Mercury", false],
  },
  {
    id: 8,
    question: `What geometric shape is generally used for stop signs?`,
    answerA: ["Triangle", false],
    answerB: ["Hexagon", false],
    answerC: ["Circle", false],
    answerD: ["Octagon", true],
  },
  {
    id: 9,
    question: `Which of these movies did Jeff Bridges not star in?`,
    answerA: ["Iron Man", false],
    answerB: ["The Big Lebowsky", false],
    answerC: ["Reservoir Dogs", true],
    answerD: ["Tron: Legacy", false],
  },
  {
    id: 10,
    question: `What is the real name of "Bono", singer of u2?`,
    answerA: ["Mark Ronson", false],
    answerB: ["Paul David Hewson", true],
    answerC: ["Lonnie Donegan", false],
    answerD: ["Calum Scott", false],
  },
  {
    id: 11,
    question: `What is the name of the famous plumber's brother, star of videogames?`,
    answerA: ["Luigi", true],
    answerB: ["Wario", false],
    answerC: ["Mario", false],
    answerD: ["Yoshi", false],
  },
  {
    id: 12,
    question: `The greek god Poseidon was the god of what?`,
    answerA: ["Fire", false],
    answerB: ["War", false],
    answerC: ["Sun", false],
    answerD: ["The Sea", true],
  },
  {
    id: 13,
    question: `Kanye West at 2009 VMA Awards interrupted which celebrity?`,
    answerA: ["Madonna", false],
    answerB: ["Beyonce", false],
    answerC: ["Taylor Swift", true],
    answerD: ["Kelly Clarkson", false],
  },
  {
    id: 14,
    question: `What was the first sport to have been played on the moon?`,
    answerA: ["Soccer", false],
    answerB: ["Golf", true],
    answerC: ["Tennis", false],
    answerD: ["Football", false],
  },
  {
    id: 15,
    question: `Which Nirvana album had a naked baby on the cover?`,
    answerA: ["Nevermind", true],
    answerB: ["Bleach", false],
    answerC: ["In Utero", false],
    answerD: ["Incesticide", false],
  },
  {
    id: 16,
    question: `In the movie Gremlins, after what time of day should you not feed Mogwai?`,
    answerA: ["Evening", false],
    answerB: ["Midnight", true],
    answerC: ["Afternoon", false],
    answerD: ["Morning", false],
  },
  {
    id: 17,
    question: `In 1939, Britain and France declared war on Germany after it invaded which country?`,
    answerA: ["Czechoslovakia", false],
    answerB: ["Austria", false],
    answerC: ["Poland", true],
    answerD: ["Hungary", false],
  },
  {
    id: 18,
    question: `What is the smallest country in the world?`,
    answerA: ["Monaco", false],
    answerB: ["Malta", false],
    answerC: ["Maldives", false],
    answerD: ["Vatican City", true],
  },
  {
    id: 19,
    question: `How many sides does a trapezium have?`,
    answerA: ["4", true],
    answerB: ["3", false],
    answerC: ["5", false],
    answerD: ["6", false],
  },
  {
    id: 20,
    question: `Which country will host the 2022 FIFA World Cup?`,
    answerA: ["Japan", false],
    answerB: ["Qatar", true],
    answerC: ["Russia", false],
    answerD: ["Sout Africa", false],
  },
  {
    id: 21,
    question: `What breed of dog was Marley in the film "Marley & Me"(2008)?`,
    answerA: ["Dalmatian", false],
    answerB: ["Golden Retriever", false],
    answerC: ["Labrador Retriever", true],
    answerD: ["Shiba Inu", false],
  },
  {
    id: 22,
    question: `Who wrote "Harry Potter"?`,
    answerA: ["J.R.R. Tolkien", false],
    answerB: ["Terry Pratchett", false],
    answerC: ["Daniel Radcliffe", false],
    answerD: ["J.K. Rowling", true],
  },
  {
    id: 23,
    question: `Who starred as Bruce Wayne/Batman in Tim Burton's 1989 movie "Batman"?`,
    answerA: ["Michael Keaton", true],
    answerB: ["George Clooney", false],
    answerC: ["Christian Bale", false],
    answerD: ["Val Kilmer", false],
  },
  {
    id: 24,
    question: `In golf, what name is given to a hole score of two under par?`,
    answerA: ["Albatross", false],
    answerB: ["Eagle", true],
    answerC: ["Birdie", false],
    answerD: ["Bogey", false],
  },
  {
    id: 25,
    question: `Who starred in the film 1973 movie "Enter The Dragon"?`,
    answerA: ["Jet Li", false],
    answerB: ["Jackie Chan", false],
    answerC: ["Bruce Lee", true],
    answerD: ["Donnie Yen", false],
  },
  {
    id: 26,
    question: `Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?`,
    answerA: ["Hercules", false],
    answerB: ["Odysseus", false],
    answerC: ["Daedalus", false],
    answerD: ["Jason", true],
  },
  {
    id: 27,
    question: `Which American president appears on a one dollar bill?`,
    answerA: ["George Washington", true],
    answerB: ["Benjamin Franklin", false],
    answerC: ["Thomas Jefferson", false],
    answerD: ["Abraham Lincoln", false],
  },
  {
    id: 28,
    question: `What is the shape of the toy invented by Hungarian professor Ernő Rubik?`,
    answerA: ["Sphere", false],
    answerB: ["Cube", true],
    answerC: ["Cylinder", false],
    answerD: ["Pyramid", false],
  },
  {
    id: 29,
    question: `Which country has hosted the 2006 FIFA World Cup?`,
    answerA: ["South Africa", false],
    answerB: ["Italy", false],
    answerC: ["Germany", true],
    answerD: ["Brazil", false],
  },
  {
    id: 30,
    question: `What is the French word for "hat"?`,
    answerA: ["Casquette", false],
    answerB: ["Bonnet", false],
    answerC: ["Casque", false],
    answerD: ["Chapeau", true],
  },
  {
    id: 31,
    question: `The human heart has how many chambers?`,
    answerA: ["4", true],
    answerB: ["2", false],
    answerC: ["3", false],
    answerD: ["6", false],
  },
  {
    id: 32,
    question: `Who created the "Metal Gear" Series?`,
    answerA: ["Shigeru Miyamoto", false],
    answerB: ["Hideo Kojima", true],
    answerC: ["Hiroshi Yamauchi", false],
    answerD: ["Gunpei Yokoi", false],
  },
  {
    id: 33,
    question: `What is the Zodiac symbol for Gemini?`,
    answerA: ["Fish", false],
    answerB: ["Maiden", false],
    answerC: ["Twins", true],
    answerD: ["Scales", false],
  },
  {
    id: 34,
    question: `The Nike apparel and footwear brand takes it's name from the Greek goddess of what?`,
    answerA: ["Strength", false],
    answerB: ["Courage", false],
    answerC: ["Honor", false],
    answerD: ["Victory", true],
  },
  {
    id: 35,
    question: `Foie gras is a French delicacy typically made from what part of a duck or goose?`,
    answerA: ["Liver", true],
    answerB: ["Stomach", false],
    answerC: ["Heart", false],
    answerD: ["Intestines", false],
  },
  {
    id: 36,
    question: `What is the german word for taking pleasure in others pain?`,
    answerA: ["Verkehrsmittel", false],
    answerB: ["Schadenfreude", true],
    answerC: ["Feldschlösschen", false],
    answerD: ["Einkaufsmöglichkeiten", false],
  },
  {
    id: 37,
    question: `What does CPU stand for?`,
    answerA: ["Central Process Unit", false],
    answerB: ["Computer Personal Unit", false],
    answerC: ["Central Processing Unit", true],
    answerD: ["Central Processor Unit", false],
  },
  {
    id: 38,
    question: `Which is the mobile OS held the largest market share in 2012?`,
    answerA: ["Symbian", false],
    answerB: ["Android", false],
    answerC: ["BlackBerry", false],
    answerD: ["iOS", true],
  },
  {
    id: 39,
    question: `In computing, what does LAN stand for?`,
    answerA: ["Long Antenna Node", false],
    answerB: ["Local Area Network", true],
    answerC: ["Light Access Node", false],
    answerD: ["Land Address Navigation", false],
  },
  {
    id: 40,
    question: `Which is the fastest land's animal in the world`,
    answerA: ["Pronghorn Antelope", false],
    answerB: ["Thomson's Gazelle", false],
    answerC: ["Cheetah", true],
    answerD: ["Lion", false],
  },
  {
    id: 41,
    question: `How many legs do butterflies have?`,
    answerA: ["0", false],
    answerB: ["2", false],
    answerC: ["4", false],
    answerD: ["6", true],
  },
  {
    id: 42,
    question: `Who painted the Sistine Chapel`,
    answerA: ["Michelangelo", true],
    answerB: ["Leonardo da Vinci", false],
    answerC: ["Raphael", false],
    answerD: ["Pablo Picasso", false],
  },
  {
    id: 43,
    question: `Who designed the Chupa Chups logo?`,
    answerA: ["Andy Warhol", false],
    answerB: ["Salvador Dali", true],
    answerC: ["Pablo Picasso", false],
    answerD: ["Jean-Michel Basquiat", false],
  },
  {
    id: 44,
    question: `What is not a wind instrument?`,
    answerA: ["Oboe", false],
    answerB: ["Didgeridoo ", false],
    answerC: ["Viola", true],
    answerD: ["Trombone", false],
  },
  {
    id: 45,
    question: `What is the primary addictive substance found in tobacco?`,
    answerA: ["Ephedrine", false],
    answerB: ["Cathinone", false],
    answerC: ["Glaucine", false],
    answerD: ["Nicotine", true],
  },
  {
    id: 46,
    question: `Which driver has been the Formula 1 world champion for a record 7 times as Michael Schumacher?`,
    answerA: ["Lewis Hamilton", true],
    answerB: ["Ayrton Senna", false],
    answerC: ["Juan Manuel Fangio", false],
    answerD: ["Fernando Alonso", false],
  },
  {
    id: 47,
    question: `How many differently shaped Tetris pieces are there?`,
    answerA: ["5", false],
    answerB: ["7", true],
    answerC: ["6", false],
    answerD: ["9", false],
  },
  {
    id: 48,
    question: `How many stars are featured on New Zealand's flag?`,
    answerA: ["5", false],
    answerB: ["0", false],
    answerC: ["4", true],
    answerD: ["3", false],
  },
  {
    id: 49,
    question: `What is the alter-ego of the DC comics character "Superman"`,
    answerA: ["John Jones", false],
    answerB: ["Bruce Wayne", false],
    answerC: ["Arthur Curry", false],
    answerD: ["Clark Kent", true],
  },
];

export default dataOne;
